FROM node:20-alpine AS builder
WORKDIR /usr/src/app
COPY package.json package-lock.json tsconfig.json next.config.mjs postcss.config.js tailwind.config.ts ./
RUN npm install
COPY . .
RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /usr/src/app
COPY package.json package-lock.json .
RUN npm install --production
COPY --from=builder /usr/src/app/.next .next
COPY --from=builder /usr/src/app/public ./public
COPY --from=builder /usr/src/app/next.config.mjs ./next.config.mjs
EXPOSE 3000
CMD ["npm", "run", "start"]
